/* HoloLab i18n — 中英双语界面文案（纯静态，零依赖） */
(function (w) {
  var LANG_KEY = 'hololab-lang';

  var dict = {
    // 导航
    nav_gallery:     { zh: '展厅',      en: 'Gallery' },
    nav_create:      { zh: '创造',      en: 'Create' },
    nav_github:      { zh: 'GitHub',    en: 'GitHub' },
    theme_label:     { zh: '切换主题',  en: 'Toggle theme' },
    lang_label:      { zh: 'Switch to English', en: '切换到中文' },

    // Hero
    hero_eyebrow:    { zh: 'HOLOGRAPHIC COLLECTION 01', en: 'HOLOGRAPHIC COLLECTION 01' },
    hero_title:      { zh: '会随着你的视线流动的光影收藏。', en: 'A collection of light that flows with your gaze.' },
    hero_sub:        { zh: '每一张卡都由 AI 分层绘制、Blender 渲染、Three.js 实时合成——拖一拖，主体往前凸，背景往后退，镭射彩虹随角度流转。', en: 'Every card is layered by AI, rendered in Blender and composited live in Three.js — drag to push the subject forward, ease the background back, and watch rainbow foil shift with the angle.' },
    hero_cta_gallery:{ zh: '进入展厅',  en: 'Enter the gallery' },
    hero_cta_create: { zh: '开始创造',  en: 'Start creating' },
    scroll_hint:     { zh: '向下滚动，进入展厅', en: 'Scroll to enter the gallery' },

    // 统计
    stat_cards:      { zh: '张卡',      en: 'cards' },
    stat_seedream:   { zh: '豆包 Seedream 生成', en: 'Generated by Doubao Seedream' },
    stat_blender:    { zh: 'Blender 渲染', en: 'Rendered in Blender' },
    stat_static:     { zh: '纯静态 · 零后端', en: 'Static · zero backend' },

    // 筛选
    filters_all:     { zh: '全部',      en: 'All' },

    // 画廊
    empty:           { zh: '暂无卡片，稍后再来看看。', en: 'No cards yet — check back soon.' },

    // 尾部 CTA
    cta_title:       { zh: '展厅里的卡，都是这样造出来的', en: 'Every card here is made like this' },
    cta_sub:         { zh: 'AI 四层素材 → Blender 渲染 → Three.js 查看器 → 纯静态发布。输入一句话，管线自动完成。', en: 'AI layered assets → Blender render → Three.js viewer → static deploy. Type one sentence — the pipeline does the rest.' },
    cta_btn:         { zh: '输入一句话，开始创造', en: 'Create from a sentence' },

    // 页脚
    footer_slogan:   { zh: '光随手动，画有余深。', en: 'Light follows your hand; depth lives in every frame.' },
    footer_tag:      { zh: 'HoloLab Studio — 作品集项目 · AI × 3D 交叉方向', en: 'HoloLab Studio — portfolio project · AI × 3D intersection' },

    // 创造页
    cr_eyebrow:      { zh: 'HOLOLAB CREATE · 创作工坊', en: 'HOLOLAB CREATE · Studio' },
    cr_title:        { zh: '一句话，造一张全息卡。', en: 'One sentence. One holographic card.' },
    cr_sub:          { zh: '展厅里的每一张卡都来自同一条管线：文字模型把你的想法写成卡面配置，AI 分层绘制素材，Blender 合成 3D 卡体，一键发布上线。输入你的创意，先看看它会变成什么——想要真卡，复制命令到本地跑一遍即可。', en: 'Every card in the gallery comes from the same pipeline: a text model turns your idea into a card config, AI paints layered assets, Blender builds the 3D body, and one command ships it. Type your idea to see how it enters the pipeline — for a real card, copy the command and run it locally.' },
    cr_label:        { zh: '你的创意一句话', en: 'Your idea in one sentence' },
    cr_ph:           { zh: '例如：给一只在月球上钓鱼的橘猫设计一张全息收藏卡', en: 'e.g. A holographic card of an orange cat fishing on the moon' },
    cr_go:           { zh: '开始创造',  en: 'Create' },
    cr_hint_pre:     { zh: '想不到写什么？', en: 'Out of ideas? ' },
    cr_hint_btn:     { zh: '给我一个示例', en: 'Give me an example' },
    pv_head:         { zh: '概念预演',  en: 'Concept preview' },
    pv_note:         { zh: '文字模型、分层绘制与渲染由本地管线完成，这里展示你的创意如何进入管线', en: 'The text model, layered painting and rendering run in your local pipeline — here is how your idea enters it' },
    pv_brief:        { zh: 'BRIEF · 创意简报', en: 'BRIEF' },
    pv_await:        { zh: '等待管线',  en: 'Waiting' },
    pv_drawing:      { zh: 'AI 绘制中…', en: 'AI painting…' },
    pv_done:         { zh: '完成 · 四层就绪', en: 'Done · 4 layers ready' },
    layer_subject:   { zh: 'SUBJECT · 主体层', en: 'SUBJECT' },
    layer_bg:        { zh: 'BACKGROUND · 背景层', en: 'BACKGROUND' },
    layer_lineart:   { zh: 'LINEART · 线稿层', en: 'LINEART' },
    layer_text:      { zh: 'TEXT · 文字层', en: 'TEXT' },
    pstep_1:         { zh: '文字模型把一句话写成卡面配置', en: 'Text model writes the card config' },
    pstep_2:         { zh: 'AI 分层绘制主体 / 背景 / 线稿 / 文字', en: 'AI paints subject / background / lineart / text' },
    pstep_3:         { zh: '抠图与线稿提取，素材对齐', en: 'Matting & lineart extraction, assets aligned' },
    pstep_4:         { zh: 'Blender 合成 3D 卡体，Cycles 渲染', en: 'Blender builds the 3D body, Cycles renders' },
    pstep_5:         { zh: '一键发布：压缩 + 预览动画 + 清单', en: 'One-command publish: compress + preview + manifest' },
    pstep_6:         { zh: '上线展厅，任何人打开即玩', en: 'Ships to the gallery for anyone to open' },
    pstep_done:      { zh: '完成',      en: 'Done' },
    cmd_title:       { zh: '想要真卡？复制命令，本地跑一遍', en: 'Want the real card? Copy the command, run it locally' },
    cmd_sub:         { zh: '在线展厅是纯静态页面，不携带任何密钥。真实生成在本地完成：克隆仓库 → 一句话出卡 → 一键发布，全程约几分钟，管线完全开源可复现。', en: 'This gallery is a static page with no keys. Real generation runs locally: clone → one-sentence card → one-command publish. It takes minutes, and the pipeline is fully open source.' },
    cmd_step1_t:     { zh: '1 · 克隆仓库', en: '1 · Clone the repo' },
    cmd_step1_d:     { zh: 'git clone 拉取全部管线源码与文档。', en: 'git clone pulls the full pipeline source and docs.' },
    cmd_step2_t:     { zh: '2 · 一句话出卡', en: '2 · One-sentence card' },
    cmd_step2_d:     { zh: '文字模型自动生成卡面配置、编号与渲染参数（需在 .env 配置豆包 API Key）。', en: 'The text model writes the config, numbering and render params (set your Doubao API key in .env).' },
    cmd_step3_t:     { zh: '3 · 一键发布', en: '3 · One-command publish' },
    cmd_step3_d:     { zh: '压缩素材、渲染预览动画、更新清单，push 后 GitHub Actions 自动上线。', en: 'Compress, render the preview, update the manifest — GitHub Actions deploys on push.' },
    cmd_copy:        { zh: '复制命令',  en: 'Copy command' },
    cmd_copied:      { zh: '已复制',    en: 'Copied' },
    note_title:      { zh: '为什么不在网页里直接生成？', en: 'Why not generate right in the page?' },
    note_1:          { zh: '一条完整的生成链需要调用豆包 API（密钥绝不能进入前端）并在本地跑 Blender 渲染。这是有意的架构取舍：', en: 'A full generation chain needs the Doubao API (keys must never enter the frontend) and local Blender rendering. This is a deliberate architecture choice:' },
    note_strong:     { zh: '展厅负责"看"，管线负责"造"', en: 'the gallery shows, the pipeline makes' },
    note_2:          { zh: '，两者解耦后，任何人都能长期打开展厅，而创作者拥有全部控制权。管线原理见 ', en: ' — decoupled, the gallery stays open to anyone while creators keep full control. See ' },
    note_links:      { zh: 'README 与 docs/', en: 'README and docs/' },
    note_3:          { zh: '（架构、AI 管线、图形学、白皮书）。', en: ' (architecture, AI pipeline, graphics, whitepaper).' },
    // 卡面占位
    mc_tag:          { zh: 'HOLOGRAPHIC COLLECTION', en: 'HOLOGRAPHIC COLLECTION' }
  };

  function detect() {
    var saved = null;
    try { saved = localStorage.getItem(LANG_KEY); } catch (e) {}
    // URL 参数优先（分享链接强制语言），其次用户选择，最后浏览器语言
    var m = location.search.match(/[?&]lang=(zh|en)/);
    if (m) return m[1];
    if (saved === 'zh' || saved === 'en') return saved;
    var nav = (navigator.language || 'zh').toLowerCase();
    return nav.indexOf('zh') === 0 ? 'zh' : 'en';
  }

  var lang = detect();
  function t(key) {
    var e = dict[key];
    return e ? e[lang] : key;
  }
  function apply() {
    document.documentElement.lang = lang === 'zh' ? 'zh-CN' : 'en';
    var nodes = document.querySelectorAll('[data-i18n],[data-i18n-ph]');
    for (var i = 0; i < nodes.length; i++) {
      var ph = nodes[i].getAttribute('data-i18n-ph');
      if (ph) nodes[i].placeholder = t(ph);
      var k = nodes[i].getAttribute('data-i18n');
      if (!k) continue;
      var v = t(k);
      if (nodes[i].tagName === 'INPUT') { nodes[i].value = v; continue; }
      nodes[i].textContent = v;
      if (nodes[i].getAttribute('data-i18n-title')) nodes[i].title = v;
    }
    var metas = document.querySelectorAll('meta[data-i18n-desc]');
    for (var j = 0; j < metas.length; j++) metas[j].content = t(metas[j].getAttribute('data-i18n-desc'));
  }
  function setLang(l) {
    lang = l;
    try { localStorage.setItem(LANG_KEY, l); } catch (e) {}
    apply();
    if (w.__hololabOnLang) w.__hololabOnLang(l);
  }

  w.HoloLabI18n = { t: t, apply: apply, setLang: setLang, get: function () { return lang; } };
})(window);
